version: "3"
services:
  go-starter:
    image: purposeinplay/go-starter-grpc-gateway
    build:
      context: ../
      dockerfile: ./d8t/Dockerfile.dev
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 7350:7350
      - 7349:7349
    environment:
      SERVER_TYPE: grpc
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12.10-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: gostarter
      POSTGRES_PASSWORD: gostarter
      POSTGRES_DB: gostarter
    ports:
      - 5432:5432
